<a href="https://colab.research.google.com/github/abdullahmazhar51/NLP-PATTERN/blob/master/nlp_BOW_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from nltk.tokenize import word_tokenize

In [0]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
text = "my name is khan! and i am not a terrorist :)"

In [0]:
print(word_tokenize(text))

['my', 'name', 'is', 'khan', '!', 'and', 'i', 'am', 'not', 'a', 'terrorist', ':', ')']


In [0]:
import re
import numpy as np


In [0]:
text = ['it was the best of times in times of india',
 'it was the worst of times in times of europe',
 'it was the age of wisdom for age of empire',
 'it was the age of foolishness in the age of foolishness']


In [0]:
from nltk.tokenize import sent_tokenize

In [0]:
from nltk.corpus import stopwords

In [0]:
import numpy as np

Tokenization

In [0]:
 token = []
 for i in range(len(text)):
  word = []
  text[i] = text[i].lower()
  text[i] = re.sub(r'\W', " ", text[i])
  text[i] = re.sub(r'\s+', " ", text[i])
  word = word_tokenize(text[i])

  for w in word:
   if w not in token:
     token.append(w)
    

token

['it',
 'was',
 'the',
 'best',
 'of',
 'times',
 'in',
 'india',
 'worst',
 'europe',
 'age',
 'wisdom',
 'for',
 'empire',
 'foolishness']

Stopwords

In [0]:

ignore = set(stopwords.words("english"))

clean_text = [t for t in token  if t not in ignore]

 

In [0]:
clean_text

['best',
 'times',
 'india',
 'worst',
 'europe',
 'age',
 'wisdom',
 'empire',
 'foolishness']

In [0]:
it was the best time in india: [1 1 1 0 0]
it was the worst time in europe time: [0 2 0 1 1]
[best time india worst europe]

**Bag of Words**

In [60]:
for t in text:
  bag_vector = np.zeros(len(clean_text))
  for i,word in enumerate(clean_text):
    if word in t:
      bag_vector[i] += 1
  print(bag_vector)

[1. 1. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 1. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 1. 1. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 1.]
